openapi: 3.0.4
info:
  title: API de Oportunidades
  description: |-
    API de integração de Oportunidades.
  contact:
    email: ti@fretatech.com.br
  version: 1.0.0
servers:
  - url: https://fretatech.com.br/api
tags:
  - name: Oportunidades
    description: Operações com oportunidades
paths:
  /opportunity:
    post:
      tags:
        - Oportunidades
      summary: Criação de oportunidade
      description: Adiciona nova oportunidade
      operationId: createOpportunity
      requestBody:
        description: Adiciona nova oportunidade
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OpportunityRequest'
          application/xml:
            schema:
              $ref: '#/components/schemas/OpportunityRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OpportunityRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpportunityResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/OpportunityResponse'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - bearerAuth: []
  /opportunity/{id}:
    post:
      tags:
        - Oportunidades
      summary: Edição de oportunidade
      description: Atualiza uma oportunidade existente
      operationId: updateOpportunity
      parameters:
        - name: id
          in: path
          description: ID da oportunidade
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Dados para atualizar a oportunidade
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OpportunityRequest'
          application/xml:
            schema:
              $ref: '#/components/schemas/OpportunityRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OpportunityRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpportunityResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/OpportunityResponse'
        '400':
          description: Invalid input
        '404':
          description: Opportunity not found
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - bearerAuth: []
    delete:
      tags:
        - Oportunidades
      summary: Exclusão de oportunidade
      description: Remove uma oportunidade existente
      operationId: deleteOpportunity
      parameters:
        - name: id
          in: path
          description: ID da oportunidade
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/DeleteResponse'
        '404':
          description: Opportunity not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - bearerAuth: []
components:
  schemas:
    OpportunityRequest:
      type: object
      properties:
        source:
          type: string
          example: "primeira"
          description: "Origem da oportunidade"
        external_id:
          type: string
          example: "abc123"
          nullable: true
        description:
          type: string
          nullable: true
          example: "a"
        customer:
          $ref: '#/components/schemas/Customer'
        fields:
          type: array
          items:
            $ref: '#/components/schemas/Field'
      required:
        - source
        - customer
        - fields
      xml:
        name: opportunityRequest
    Opportunity:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 12
          nullable: true
        external_id:
          type: string
          example: "abc123"
          nullable: true
        description:
          type: string
          nullable: true
          example: "a"
        source:
          type: string
          example: "primeira"
        customer:
          $ref: '#/components/schemas/Customer'
        fields:
          type: array
          items:
            $ref: '#/components/schemas/Field'
      xml:
        name: opportunity
    Customer:
      type: object
      properties:
        name:
          type: string
          example: "Maria da Silva"
        email:
          type: string
          format: email
          example: "email@email.com"
        phone:
          type: string
          nullable: true
          example: null
      xml:
        name: customer
    Field:
      type: object
      properties:
        label:
          type: string
          example: "Data de ida"
        value:
          type: string
          example: "20/05/2026"
      xml:
        name: field
    OpportunityResponse:
      type: object
      properties:
        msg:
          type: string
          example: "Oportunidade criada com sucesso"
        opportunity:
          $ref: '#/components/schemas/Opportunity'
      xml:
        name: opportunityResponse
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    DeleteResponse:
      type: object
      properties:
        msg:
          type: string
          example: "Oportunidade excluída com sucesso"
      xml:
        name: deleteResponse
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
